service: aws-serverless-node-core

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 1024

functions:
  ping:
    handler: dist/ping.handler
    timeout: 29
    events:
      - http:
          method: GET
          path: /ping

package:
  individually: true
