service: aws-serverless-node-core

frameworkVersion: '4'

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  environment:
    DB_URI: ${ssm:/sls-node-core-${self:custom.stage}/DB_URI}

functions:
  ping:
    handler: dist/ping.handler
    timeout: 29
    events:
      - http:
          method: GET
          path: /ping

package:
  individually: true
