service: aws-serverless-node-core

frameworkVersion: '4'

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 1024
  stage: ${opt:stage, 'prod'}
  environment:
    DB_URI: ${ssm:/sls-node-core-${self:custom.stage}/DB_URI}
    JWT_SECRET: ${ssm:/sls-node-core-${self:custom.stage}/JWT_SECRET}

functions:
  ping:
    handler: dist/handlers/ping.handler
    timeout: 29
    events:
      - http:
          method: GET
          path: /ping
  signup:
    handler: dist/handlers/signup.handler
    timeout: 29
    events:
      - http:
          method: POST
          path: /signup

package:
  individually: true
